Repository inspirehep/inspire-schemas, pull requests merged in 2018-03, with the labels that each got.

#309 data: add dois field
  inspire_schemas/records/data.yml
  tests/integration/fixtures/data_example.json
Labels: Review: Ready for Review

#310 builders: normalize dates in LiteratureBuilder
  inspire_schemas/builders/literature.py
  tests/unit/test_literature_builder.py
Labels: Review: WIP

#311 utils: addition of ``draft`` validation
  inspire_schemas/utils.py
  tests/unit/test_utils.py
Labels: Review: In Review

#312 builders: fix urls in ReferenceBuilder
  inspire_schemas/builders/references.py
  inspire_schemas/utils.py
  tests/unit/test_reference_builder.py
  tests/unit/test_utils.py
Labels: Review: WIP
